require 'i18n'
require 'terminal-table'
require 'new_super_codebreaker_2021'

require_relative 'config/i18n'
require_relative 'codebreaker_console/view'
require_relative 'codebreaker_console/user_creation'
require_relative 'codebreaker_console/game'
require_relative 'codebreaker_console/menu'
require_relative 'codebreaker_console/show_stats'
